name: build & upload

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    strategy:
      matrix:
        #[macos,ubuntu, windows]
        os: [ubuntu]
        onf-version: [v0.1.0]
    runs-on:  ${{ matrix.os }}-latest
    steps:
    - name: version check
      uses: marceloprado/has-changed-path@v1
      id: version
      with:
        paths: ./VERSION

    - name: read version
      uses: pCYSl5EDgo/cat@master
      id: onf-version
      with:
        path: VERSION
    
    - name: onf upgrade
      uses: "OnFinality-io/action-onf-release@v1"
      with:
        onf-access-key: "${{ secrets.ONF_ACCESS_KEY }}"
        onf-secret-key: "${{ secrets.ONF_SECRET_KEY }}"
        onf-workspace-id: "6729563711177248768"
        onf-network-key: 29153103-7641-400e-90aa-35b7ee1f30d5
        onf-sub-command: image # node, image
        onf-action: add # upgrade, add
        image-version: ${{ steps.onf-version.outputs.text }}
        percent: 30


    
    
    
    
    
    
    
    